### ISSUE TITLE
Added value: secure implementation: Forbid sw AES or give pseudocode for the round function?

### ISSUE THREAD

**Issue by fscoto** [jedisct1/draft-aegis-aead#40]
As per meeting 2022-03-09, the RFC draft should have as much added value as we can possibly cram into it, in particular regarding secure implementation. The AES round function is, other than nonce handling and poor key derivation, the most obvious way to get implementation wrong. However, the AES round function involves an S-box, leading to straightforward and well-studied timing attacks. I see two options to deal with this:

1. Provide full pseudocode (including about 2000 lines of bitsliced S-box code) for processing a block with the round function.
2. Make hardware support for AES a hard requirement by specification.

(I will take this opportunity to humorously point out I'd participated in the meeting yesterday from a laptop without hardware AES support. Fortunately, none of the parties interested in AES have such problems.)

**Comment by jedisct1** [comment]
I think this is out of scope, and should be addressed in a different document specifically about software AES implementations.

Bitslicing/fixslicing/masking is not necessarily required. For example, some implementations in the Linux kernel are just pre-loading every cache line instead. Which is perfectly fine and way faster.

This needs proper analysis, and maybe this is something we can discuss with Bart and Daniel. But, I'm not convinced that side channels are much of an issue after the state has been initialized, since what we get then is akin to a random permutation. This is very different from regular AES encryption involving a key schedule that gets reused every time.

We shouldn't forbid software implementations, nor assume that hardware implementations are safe against DPA.

**Comment by samuel-lucas6** [comment]
Could we reference a paper or something discussing how to do a secure software implementation? I don't remember the RFCs I've read mentioning bitslicing doing that. It would be more helpful than nothing, assuming such a paper exists.

**Comment by jedisct1** [comment]
The paper on [fixslicing](https://eprint.iacr.org/2020/1123.pdf) provides a good overview of other mitigation techniques, but the fixslicing technique itself is not applicable to AEGIS.

There's no single paper summarizing all the different techniques applicable to each platform AFAIK. Information is scattered everywhere.

**Comment by ericlagergren** [comment]
One of the primary benefits of AEGS is its performance, which you really only get with hardware AES. 

For example, using AEGIS-128L with 8 KiB messages I'm seeing just under 1 cycle per byte on a Cortex A-72 with AES instructions, but on a similar* Cortex A-72 without AES instructions I'm seeing just under 24 cycles per byte**.

My understanding is that bit slicing is still much slower than table lookups, which would make AEGIS-with-constant-time-software-AES even less appealing.

Perhaps the RFC could just recommend against it on performance grounds and avoid having to discuss software AES.

*: For reference, the first machine runs ChaCha20-Poly1305 at 5 cycles per byte and the second at 10 cycles per byte, so they're not exact. But clearly the difference should be 2x not 24x.
**: It's also possible that a different SW implementation could be faster. I suspect that part of the difference is because the "generic" implementation is just slower, but even then 24x is a large difference.

**Comment by jedisct1** [comment]
Software AES-GCM implementations are widely deployed; they are necessary to use a common cipher suites in heterogenous environments or to avoid having to support multiple options. The same applies to AEGIS. And software AEGIS implementations remains faster than AES-GCM (thanks to the absence of GHASH).

As an existing, practical example, dm-crypt removable volumes encrypted using AEGIS have to be mountable from any device, even if it doesn't have hardware AES support.

People will need software AEGIS implementations, so having a few words about them in the specification is probably not a bad thing.
