### ISSUE TITLE
Fail when algorithm parameters are out of range

### ISSUE THREAD

**Issue by ericlagergren** [jedisct1/draft-aegis-aead#55]
The RFC specifies the maximum permissible values for the message, additional data, etc. but does not require that the implementation reject (or prevent) parameters that are out of range.

In practice, implementations might not need to worry about 2^61 octet strings because of resource/environment constraints. But it's not strictly impossible, especially if the implementation supports an update-style API.

I looked at a few implementations, including the reference implementation, and only one rejected parameters that are out of range.

I can send a CL if you'd like.

**Comment by ericlagergren** [comment]
Additionally, this becomes more relevant if the bounds are lowered (e.g., https://github.com/jedisct1/draft-aegis-aead/issues/52).

**Comment by jedisct1** [comment]
Since the tag must be verified before releasing the plaintext, even with a streaming API, it is very unlikely that it could be a practical concern.

Still, it wouldn't hurt to mention that checks must be done, especially since the constants are defined.

Instead of making that part of the algorithm, maybe this is a constraint we can add to the inputs definitions?

```text
m: the message to be encrypted
```

->

```text
m: the message to be encrypted (MUST be less than P_MAX bytes)
```

?
